// Code generated by mockery v2.40.1. DO NOT EDIT.

package application

import (
	context "context"
	commands "eda-in-golang/depot/internal/application/commands"

	mock "github.com/stretchr/testify/mock"
)

// MockCommands is an autogenerated mock type for the Commands type
type MockCommands struct {
	mock.Mock
}

// AssignShoppingList provides a mock function with given fields: ctx, cmd
func (_m *MockCommands) AssignShoppingList(ctx context.Context, cmd commands.AssignShoppingList) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for AssignShoppingList")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.AssignShoppingList) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CancelShoppingList provides a mock function with given fields: ctx, cmd
func (_m *MockCommands) CancelShoppingList(ctx context.Context, cmd commands.CancelShoppingList) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for CancelShoppingList")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.CancelShoppingList) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CompleteShoppingList provides a mock function with given fields: ctx, cmd
func (_m *MockCommands) CompleteShoppingList(ctx context.Context, cmd commands.CompleteShoppingList) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for CompleteShoppingList")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.CompleteShoppingList) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateShoppingList provides a mock function with given fields: ctx, cmd
func (_m *MockCommands) CreateShoppingList(ctx context.Context, cmd commands.CreateShoppingList) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for CreateShoppingList")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.CreateShoppingList) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InitiateShopping provides a mock function with given fields: ctx, cmd
func (_m *MockCommands) InitiateShopping(ctx context.Context, cmd commands.InitiateShopping) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for InitiateShopping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.InitiateShopping) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockCommands creates a new instance of MockCommands. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommands(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommands {
	mock := &MockCommands{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
