// Code generated by mockery v2.40.1. DO NOT EDIT.

package depotpb

import mock "github.com/stretchr/testify/mock"

// MockUnsafeDepotServiceServer is an autogenerated mock type for the UnsafeDepotServiceServer type
type MockUnsafeDepotServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedDepotServiceServer provides a mock function with given fields:
func (_m *MockUnsafeDepotServiceServer) mustEmbedUnimplementedDepotServiceServer() {
	_m.Called()
}

// NewMockUnsafeDepotServiceServer creates a new instance of MockUnsafeDepotServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUnsafeDepotServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUnsafeDepotServiceServer {
	mock := &MockUnsafeDepotServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
