// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// StoresServiceIncreaseProductPriceBody stores service increase product price body
//
// swagger:model StoresServiceIncreaseProductPriceBody
type StoresServiceIncreaseProductPriceBody struct {

	// price
	Price float64 `json:"price,omitempty"`
}

// Validate validates this stores service increase product price body
func (m *StoresServiceIncreaseProductPriceBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this stores service increase product price body based on context it is used
func (m *StoresServiceIncreaseProductPriceBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *StoresServiceIncreaseProductPriceBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StoresServiceIncreaseProductPriceBody) UnmarshalBinary(b []byte) error {
	var res StoresServiceIncreaseProductPriceBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
