// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// BasketServiceRemoveItemBody basket service remove item body
//
// swagger:model BasketServiceRemoveItemBody
type BasketServiceRemoveItemBody struct {

	// product Id
	ProductID string `json:"productId,omitempty"`

	// quantity
	Quantity int32 `json:"quantity,omitempty"`
}

// Validate validates this basket service remove item body
func (m *BasketServiceRemoveItemBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this basket service remove item body based on context it is used
func (m *BasketServiceRemoveItemBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *BasketServiceRemoveItemBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BasketServiceRemoveItemBody) UnmarshalBinary(b []byte) error {
	var res BasketServiceRemoveItemBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
