// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// BasketServiceCheckoutBasketBody basket service checkout basket body
//
// swagger:model BasketServiceCheckoutBasketBody
type BasketServiceCheckoutBasketBody struct {

	// payment Id
	PaymentID string `json:"paymentId,omitempty"`
}

// Validate validates this basket service checkout basket body
func (m *BasketServiceCheckoutBasketBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this basket service checkout basket body based on context it is used
func (m *BasketServiceCheckoutBasketBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *BasketServiceCheckoutBasketBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BasketServiceCheckoutBasketBody) UnmarshalBinary(b []byte) error {
	var res BasketServiceCheckoutBasketBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
