// Code generated by mockery v2.40.1. DO NOT EDIT.

package domain

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockShoppingRepository is an autogenerated mock type for the ShoppingRepository type
type MockShoppingRepository struct {
	mock.Mock
}

// Cancel provides a mock function with given fields: ctx, shoppingID
func (_m *MockShoppingRepository) Cancel(ctx context.Context, shoppingID string) error {
	ret := _m.Called(ctx, shoppingID)

	if len(ret) == 0 {
		panic("no return value specified for Cancel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, shoppingID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: ctx, orderID, items
func (_m *MockShoppingRepository) Create(ctx context.Context, orderID string, items []Item) (string, error) {
	ret := _m.Called(ctx, orderID, items)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []Item) (string, error)); ok {
		return rf(ctx, orderID, items)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []Item) string); ok {
		r0 = rf(ctx, orderID, items)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []Item) error); ok {
		r1 = rf(ctx, orderID, items)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockShoppingRepository creates a new instance of MockShoppingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockShoppingRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockShoppingRepository {
	mock := &MockShoppingRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
