// Code generated by go-swagger; DO NOT EDIT.

package customer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"eda-in-golang/customers/customersclient/models"
)

// CreateCustomerReader is a Reader for the CreateCustomer structure.
type CreateCustomerReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateCustomerReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateCustomerOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewCreateCustomerDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCreateCustomerOK creates a CreateCustomerOK with default headers values
func NewCreateCustomerOK() *CreateCustomerOK {
	return &CreateCustomerOK{}
}

/*
CreateCustomerOK describes a response with status code 200, with default header values.

A successful response.
*/
type CreateCustomerOK struct {
	Payload *models.CustomerspbRegisterCustomerResponse
}

// IsSuccess returns true when this create customer o k response has a 2xx status code
func (o *CreateCustomerOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create customer o k response has a 3xx status code
func (o *CreateCustomerOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create customer o k response has a 4xx status code
func (o *CreateCustomerOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this create customer o k response has a 5xx status code
func (o *CreateCustomerOK) IsServerError() bool {
	return false
}

// IsCode returns true when this create customer o k response a status code equal to that given
func (o *CreateCustomerOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the create customer o k response
func (o *CreateCustomerOK) Code() int {
	return 200
}

func (o *CreateCustomerOK) Error() string {
	return fmt.Sprintf("[POST /api/customers][%d] createCustomerOK  %+v", 200, o.Payload)
}

func (o *CreateCustomerOK) String() string {
	return fmt.Sprintf("[POST /api/customers][%d] createCustomerOK  %+v", 200, o.Payload)
}

func (o *CreateCustomerOK) GetPayload() *models.CustomerspbRegisterCustomerResponse {
	return o.Payload
}

func (o *CreateCustomerOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CustomerspbRegisterCustomerResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateCustomerDefault creates a CreateCustomerDefault with default headers values
func NewCreateCustomerDefault(code int) *CreateCustomerDefault {
	return &CreateCustomerDefault{
		_statusCode: code,
	}
}

/*
CreateCustomerDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type CreateCustomerDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this create customer default response has a 2xx status code
func (o *CreateCustomerDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this create customer default response has a 3xx status code
func (o *CreateCustomerDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this create customer default response has a 4xx status code
func (o *CreateCustomerDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this create customer default response has a 5xx status code
func (o *CreateCustomerDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this create customer default response a status code equal to that given
func (o *CreateCustomerDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the create customer default response
func (o *CreateCustomerDefault) Code() int {
	return o._statusCode
}

func (o *CreateCustomerDefault) Error() string {
	return fmt.Sprintf("[POST /api/customers][%d] createCustomer default  %+v", o._statusCode, o.Payload)
}

func (o *CreateCustomerDefault) String() string {
	return fmt.Sprintf("[POST /api/customers][%d] createCustomer default  %+v", o._statusCode, o.Payload)
}

func (o *CreateCustomerDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *CreateCustomerDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
