// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// StoresServiceRebrandStoreBody stores service rebrand store body
//
// swagger:model StoresServiceRebrandStoreBody
type StoresServiceRebrandStoreBody struct {

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this stores service rebrand store body
func (m *StoresServiceRebrandStoreBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this stores service rebrand store body based on context it is used
func (m *StoresServiceRebrandStoreBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *StoresServiceRebrandStoreBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StoresServiceRebrandStoreBody) UnmarshalBinary(b []byte) error {
	var res StoresServiceRebrandStoreBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
