// Code generated by mockery v2.40.1. DO NOT EDIT.

package storespb

import mock "github.com/stretchr/testify/mock"

// MockUnsafeStoresServiceServer is an autogenerated mock type for the UnsafeStoresServiceServer type
type MockUnsafeStoresServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedStoresServiceServer provides a mock function with given fields:
func (_m *MockUnsafeStoresServiceServer) mustEmbedUnimplementedStoresServiceServer() {
	_m.Called()
}

// NewMockUnsafeStoresServiceServer creates a new instance of MockUnsafeStoresServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUnsafeStoresServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUnsafeStoresServiceServer {
	mock := &MockUnsafeStoresServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
